spring:
  datasource:
    url: jdbc:mysql://localhost:3306/glovo
    username: root
    password: B9olP6_&
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
jwt:
  key: 4125442A472D4B6150645367566B59703373367639792F423F4528482B4D6251
  token-expiration: 10000
  refresh-token-expiration: 2400000
server:
  address: 0.0.0.0
